/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package agentpc.Interfaces;

import agentpc.BusinessLogic.ItemDetails;
import agentpc.DBOperations.DBOperations;
import java.awt.Color;
import java.awt.Container;
import java.awt.Toolkit;
import javax.swing.ComboBoxEditor;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;

/**
 * 
 *
 * @author Namal Jayasuriya
 */
public class NewItem extends javax.swing.JFrame {

    /**
     * Creates new form AddItem
     */
    private boolean error=false;
    DBOperations dbo=new DBOperations();
    ItemDetails id =new ItemDetails();
    
    
    public NewItem() {
        
        initComponents();
        clearFields();
        String items[]=dbo.getTypes("item","itemtype");
        String company[]=dbo.getTypes("item","suplier");
        for(int i=0;i<items.length;i++){
        this.ddItemType.addItem(items[i]);
        this.ddCompany.addItem(company[i]);
        }
        
    }
    void clearFields() {
        //this.txtCompany.setText("");
        this.txtCompanyDisc.setText("");
        this.txtComplain.setText("");
        this.txtGetPrice.setText("");
        this.txtItemName.setText("");
        //this.ddItemType.addItem(null);
        //this.ddItemType.setSelectedItem(null);//setText("");
        this.txtLabledPrice.setText("");
        this.txtQuantity.setText("");
        this.txtSellingDisc.setText("");
        this.txtSellingPrice.setText("");
        this.txtDescription.setText("");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        txtGetPrice = new javax.swing.JTextField();
        txtLabledPrice = new javax.swing.JTextField();
        txtSellingDisc = new javax.swing.JTextField();
        txtCompanyDisc = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComplain = new javax.swing.JTextArea();
        txtSellingPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        ddItemType = new javax.swing.JComboBox();
        ddCompany = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("New Item");

        jLabel2.setText("Item Name");

        jLabel3.setText("Item Type");

        jLabel4.setText("Company");

        jLabel5.setText("Get Price");

        jLabel6.setText("Labled price");

        jLabel7.setText("Selling Discount");

        jLabel8.setText("Company Discount");

        txtItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemNameActionPerformed(evt);
            }
        });
        txtItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtItemNameKeyTyped(evt);
            }
        });

        txtGetPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGetPriceActionPerformed(evt);
            }
        });
        txtGetPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGetPriceKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGetPriceKeyTyped(evt);
            }
        });

        txtLabledPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLabledPriceKeyTyped(evt);
            }
        });

        txtSellingDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSellingDiscActionPerformed(evt);
            }
        });
        txtSellingDisc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSellingDiscKeyTyped(evt);
            }
        });

        txtCompanyDisc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCompanyDiscKeyTyped(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel10.setText("Complains");

        txtComplain.setColumns(20);
        txtComplain.setRows(5);
        jScrollPane2.setViewportView(txtComplain);

        txtSellingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSellingPriceActionPerformed(evt);
            }
        });
        txtSellingPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSellingPriceKeyTyped(evt);
            }
        });

        jLabel9.setText("selling Price");

        jLabel11.setText("Quantity");

        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantityKeyTyped(evt);
            }
        });

        jLabel12.setText("Description");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        btnBack.setText("Close");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        ddItemType.setEditable(true);
        ddItemType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ddItemTypeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ddItemType, 0, 167, Short.MAX_VALUE)
                                            .addComponent(ddCompany, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(41, 41, 41)
                                        .addComponent(txtGetPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txtSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                        .addComponent(txtSellingDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtLabledPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(51, 51, 51)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCompanyDisc, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(txtQuantity))))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel10))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel12))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(btnSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBack)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ddItemType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ddCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(txtGetPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLabledPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSellingDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCompanyDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Enter Item Details");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameActionPerformed

    private void txtGetPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGetPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGetPriceActionPerformed

    private void txtSellingDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSellingDiscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSellingDiscActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        error=false;
        System.out.println(this.txtItemName.getText());
        
        
        
        if(this.txtItemName.getText().equals("")){
            this.txtItemName.setText("cannot Empty");
            this.txtItemName.setForeground(Color.red);
          error=true;
        }
        //System.out.println(ddItemType.getSelectedItem().toString()+"liusehr;kgae");
        /*if(this.ddItemType.getSelectedItem().toString().equals("")){
            //ComboBoxEditor tcA = (ComboBoxEditor) ddItemType.setEditor().setEditorComponent();
            //Container cont = getContentPane();
            //System.out.println("fghfzgxhxfgdhfzxghxf");
          this.ddItemType.addItem("cannot null");//setText("cannot null"); 
          this.ddItemType.setSelectedItem("cannot null");
          this.ddItemType.setForeground(Color.red);
          error=true;
        }
        if(this.txtCompany.getText().equals("")){
          this.txtCompany.setText("cannot null"); 
          this.txtCompany.setForeground(Color.red);
          error=true;
        }*/
        if(this.txtGetPrice.getText().equals("")){
          this.txtGetPrice.setText("Cannot Empty"); 
          this.txtGetPrice.setForeground(Color.red);
          error=true;
        }
        if(this.txtGetPrice.getText().equals("")){
          this.txtGetPrice.setText("Cannot Empty"); 
          this.txtGetPrice.setForeground(Color.red);
          error=true;
        }
        
        if(this.txtSellingPrice.getText().equals("")){
          this.txtSellingPrice.setText("Cannot Empty"); 
          this.txtSellingPrice.setForeground(Color.red);
          error=true;
        }
        if(this.txtLabledPrice.getText().equals("")){
          this.txtLabledPrice.setText("Cannot Empty"); 
          this.txtLabledPrice.setForeground(Color.red);
          error=true;
        }
        if(this.txtSellingDisc.getText().equals("")){
          this.txtSellingDisc.setText("Cannot Empty"); 
          this.txtSellingDisc.setForeground(Color.red);
          error=true;
        }
        if(this.txtCompanyDisc.getText().equals("")){
          this.txtCompanyDisc.setText("Cannot Empty"); 
          this.txtCompanyDisc.setForeground(Color.red);
          error=true;
        }
        if(this.txtQuantity.getText().equals("")){
          this.txtQuantity.setText("Cannot Empty"); 
          this.txtQuantity.setForeground(Color.red);
          error=true;
        }
        
        if (error==true){
            JOptionPane.showMessageDialog(null, "Marked Inputs exist errors");
        }
        else if(error==false){
           id.setItemID("item","itemid",this.ddItemType.getSelectedItem().toString());
           id.setItemName(this.txtItemName.getText().toLowerCase());
           id.setItemType(this.ddItemType.getSelectedItem().toString().toLowerCase());
           id.setSuplier(this.ddCompany.getSelectedItem().toString());
           id.setQuantity(Integer.parseInt(this.txtQuantity.getText()));
           id.setGetPrice(Double.parseDouble(this.txtGetPrice.getText()));
           id.setSelPrice(Double.parseDouble(this.txtSellingPrice.getText()));
           id.setLblPrice(Double.parseDouble(this.txtLabledPrice.getText()));
           id.setSalesDisc(Double.parseDouble(this.txtSellingDisc.getText()));
           id.setCompanyDisc(Double.parseDouble(this.txtCompanyDisc.getText()));
           id.setComplain(this.txtComplain.getText());
           id.setDescription(this.txtDescription.getText());
        boolean result=false;
        if(dbo.checkItem(this.ddItemType.getSelectedItem().toString(),this.txtItemName.getText())==1)
             result= dbo.addItem("item",id);
        else if(dbo.checkItem(this.ddItemType.getSelectedItem().toString(),this.txtItemName.getText())==0){
            JOptionPane.showMessageDialog(this, "this iyem is already exist");
            this.txtItemName.setForeground(Color.red);
            this.ddItemType.setForeground(Color.red);
        }
                
                if (result == true) {
                    JOptionPane.showMessageDialog(this, "Successfully Inserted as ItemID : "+id.getItemID());
                    this.dispose();
                } 
                //else {
                   // JOptionPane.showMessageDialog(this, "OOps error occured while inserting!!");
                //}
        }
            
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtSellingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSellingPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSellingPriceActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void ddItemTypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ddItemTypeKeyPressed
        // TODO add your handling code here:
        /*AutoCompleteDecorator.decorate(comboBox);
                System.out.println("Is editable - "
                        + comboBox.isEditable() + ". Surprise!");
                JOptionPane.showMessageDialog(null, comboBox);*/
    }//GEN-LAST:event_ddItemTypeKeyPressed

    private void txtGetPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGetPriceKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtGetPriceKeyPressed

    private void txtGetPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGetPriceKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        String in = this.txtGetPrice.getText();
        if(c!='.'&&!Character.isDigit(c)||( Character.isLetter(c))){
        evt.consume();
        Toolkit tk =Toolkit.getDefaultToolkit();
        tk.beep();
        }
    }//GEN-LAST:event_txtGetPriceKeyTyped

    private void txtSellingPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSellingPriceKeyTyped
        char c=evt.getKeyChar();
        String in = this.txtGetPrice.getText();
        if(c!='.'&&!Character.isDigit(c)||( Character.isLetter(c))){
        evt.consume();
        Toolkit tk =Toolkit.getDefaultToolkit();
        tk.beep();
        }
    }//GEN-LAST:event_txtSellingPriceKeyTyped

    private void txtLabledPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLabledPriceKeyTyped
        char c=evt.getKeyChar();
        String in = this.txtGetPrice.getText();
        if(c!='.'&&!Character.isDigit(c)||( Character.isLetter(c))){
        evt.consume();
        Toolkit tk =Toolkit.getDefaultToolkit();
        tk.beep();
        }
    }//GEN-LAST:event_txtLabledPriceKeyTyped

    private void txtSellingDiscKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSellingDiscKeyTyped
        char c=evt.getKeyChar();
        String in = this.txtGetPrice.getText();
        if(c!='.'&&!Character.isDigit(c)||( Character.isLetter(c))){
        evt.consume();
        Toolkit tk =Toolkit.getDefaultToolkit();
        tk.beep();
        }
    }//GEN-LAST:event_txtSellingDiscKeyTyped

    private void txtCompanyDiscKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompanyDiscKeyTyped
        char c=evt.getKeyChar();
        String in = this.txtGetPrice.getText();
        if(c!='.'&&!Character.isDigit(c)||( Character.isLetter(c))){
        evt.consume();
        Toolkit tk =Toolkit.getDefaultToolkit();
        tk.beep();
        }
    }//GEN-LAST:event_txtCompanyDiscKeyTyped

    private void txtQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyTyped
        char c=evt.getKeyChar();
        String in = this.txtGetPrice.getText();
        if(!Character.isDigit(c)||( Character.isLetter(c))){
        evt.consume();
        Toolkit tk =Toolkit.getDefaultToolkit();
        tk.beep();
        }
    }//GEN-LAST:event_txtQuantityKeyTyped

    private void txtItemNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemNameKeyTyped
        char c=evt.getKeyChar();
        String in = this.txtGetPrice.getText();
        if(!Character.isDigit(c)&&c!='_'&& !Character.isLetter(c)){
        evt.consume();
        Toolkit tk =Toolkit.getDefaultToolkit();
        tk.beep();
        }
    }//GEN-LAST:event_txtItemNameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox ddCompany;
    private javax.swing.JComboBox ddItemType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCompanyDisc;
    private javax.swing.JTextArea txtComplain;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtGetPrice;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtLabledPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSellingDisc;
    private javax.swing.JTextField txtSellingPrice;
    // End of variables declaration//GEN-END:variables
}
